In [425]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Numpy tasks

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [601]:
# Write your code here

def sigmoid(X):
    return 1 / (1 + np.exp(-X))

a = np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25])
print(sigmoid(a[-5:]))

[0.549834   0.47502081 0.52497919 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (y.reshape(-1, 1), the alternative y.T will not work because T does not work on 1D arrays).

In [602]:
# Write your code here

x = np.array([3,1,4,2,6,1,4,8])
y = np.array([5,2,3,12,2,4,17,11])

print(np.sum(x * y))
print(np.dot(x, y))
print(np.matmul(x, y.reshape(-1, 1))[0])

225
225
225


**Task 3.** Calculate value of the logistic model<br/>
$$y = \frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2]$<br/>
$\theta = [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]$<br/>
and print the result. Use only vector operations.

In [603]:
# Write your code here

def sigmoid(X):
    return 1 / (1 + np.exp(-X))
    
x = np.array([1.2,2.3,3.4,-0.7,4.2,2.7,-0.5,1.4,-3.3,0.2, 1.0]) # 1?
theta = np.array([2.7,0.33,-2.12,-1.73,2.9,-5.8,-0.9,12.11,3.43,-0.5,-1.65])

print(np.round(sigmoid(np.dot(x, theta)), 8))

0.24176998


**Task 4.** Calculate value of the multivariate linear regression model<br/>
$$y = A x + B$$
for<br/>
$A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$<br/>
$B = \begin{bmatrix} 0.2 \\ 0.3 \end{bmatrix}$<br/>
$x = [1, 2, 3]^T$<br/>
and print the result. Use only vector and matrix operations.

In [604]:
# Write your code here

A = np.array([
    [1, 2, 1],
    [3, 0, 1]
])

B = np.array([0.2, 0.3]).reshape(-1, 1)
x = np.array([1,2,3]).reshape(-1, 1)

y = np.matmul(A, x) + B
print(y)

[[8.2]
 [6.3]]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [430]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

## Merge both MovieLens DataFrames into one

In [431]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

## Pandas tasks - Steam dataset

**Task 5.** How many people made a purchase in the Steam dataset? Remember that a person could buy many games, but you need to count every person once.

In [605]:
# Write your code here

count = steam_df['user-id'].nunique()
print(count)

12393


**Task 6.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [606]:
# Write your code here

steam_df_copy = steam_df.loc[((steam_df['game-title'] == 'The Elder Scrolls V Skyrim'))].copy()
print(steam_df_copy['user-id'].nunique())

717


**Task 7.** How many purchases people made on average?

In [607]:
# Write your code here

purchases_df = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['user-id', 'game-title']]
purchases_df = purchases_df.groupby(['user-id'])[['game-title']].count()
res = purchases_df['game-title'].mean()
print(np.round(res, 2))

10.45


**Task 8.** Who bought the most games?

In [435]:
# Write your code here

steam_df.head()

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0

In [436]:
condition = steam_df['behavior-name'] == 'purchase'
purchases_df = steam_df.loc[condition, ['user-id', 'behavior-name']]
counts_df = purchases_df.groupby(['user-id']).count()
max_bought = counts_df['behavior-name'].max()
counts_df.loc[counts_df['behavior-name'] == max_bought].reset_index()['user-id'][0]

62990992

**Task 9.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [437]:
steam_df.head()

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0

In [438]:
# Write your code here

conditions = (steam_df['game-title'] == 'The Elder Scrolls V Skyrim') & (steam_df['behavior-name'] == 'play')
played_elder_scrolls_df = steam_df.loc[conditions, ['user-id', 'value']]
played_elder_scrolls_df.groupby(['user-id']).sum()['value'].mean()

104.7109305760708

**Task 10.** Which games were played the most (in terms of the number of hours played)? Display a DataFrame with the first 10 titles and respective numbers of hours.

In [439]:
steam_df.head()

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0

In [440]:
# Write your code here

condition = steam_df['behavior-name'] == 'play'
games_df = steam_df.loc[condition, ['game-title', 'value']]
res = games_df.groupby(['game-title']).sum().sort_values('value', ascending=False)[:10].reset_index()
print(res)

                                    game-title     value
0                                       Dota 2  981684.6
1              Counter-Strike Global Offensive  322771.6
2                              Team Fortress 2  173673.3
3                               Counter-Strike  134261.1
4                   Sid Meier's Civilization V   99821.3
5                        Counter-Strike Source   96075.5
6                   The Elder Scrolls V Skyrim   70889.3
7                                  Garry's Mod   49725.3
8  Call of Duty Modern Warfare 2 - Multiplayer   42009.9
9                                Left 4 Dead 2   33596.7


**Task 11.** Which games are the most consistently played (in terms of the average number of hours played)? Print a DataFrame with the first 10 titles and respective numbers of hours.

In [441]:
steam_df.head()

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0

In [442]:
steam_df.loc[steam_df['value'] == 1.0]

user-id                  game-title behavior-name  value  zero
0       151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
2       151603712                   Fallout 4      purchase    1.0     0
4       151603712                       Spore      purchase    1.0     0
6       151603712           Fallout New Vegas      purchase    1.0     0
8       151603712               Left 4 Dead 2      purchase    1.0     0
...           ...                         ...           ...    ...   ...
199990  128470551                Fallen Earth      purchase    1.0     0
199992  128470551                 Magic Duels      purchase    1.0     0
199994  128470551                 Titan Souls      purchase    1.0     0
199996  128470551  Grand Theft Auto Vice City      purchase    1.0     0
199998  128470551                        RUSH      purchase    1.0     0

[130569 rows x 5 columns]

In [443]:
# Write your code here

condition = steam_df['behavior-name'] == 'play'
games_df = steam_df.loc[condition, ['game-title', 'value']]
res = games_df.groupby(['game-title']).mean().sort_values('value', ascending=False)[:10].reset_index()
print(res)

                          game-title        value
0            Eastside Hockey Manager  1295.000000
1  Baldur's Gate II Enhanced Edition   475.255556
2                    FIFA Manager 09   411.000000
3                          Perpetuum   400.975000
4              Football Manager 2014   391.984615
5              Football Manager 2012   390.453165
6              Football Manager 2010   375.048571
7              Football Manager 2011   365.703226
8                  Freaking Meatbags   331.000000
9        Out of the Park Baseball 16   330.400000


**Task 12\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [444]:
steam_df.head()

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0

In [445]:
# Write your code here
copy_df = steam_df.copy()
condition = (copy_df['behavior-name'] == 'purchase') & (copy_df['value'] == 1.0)
copy_df.loc[condition, 'value'] = copy_df.loc[condition, 'value'] * 0
copy_df = copy_df.groupby(['user-id', 'game-title']).sum(numeric_only=True).reset_index()
games_df = copy_df.loc[:, ['game-title', 'value']]
res = games_df.groupby(['game-title']).mean().sort_values('value', ascending=False)[:10].reset_index()
print(res)

                    game-title        value
0      Eastside Hockey Manager  1295.000000
1              FIFA Manager 09   411.000000
2                    Perpetuum   400.975000
3        Football Manager 2012   385.572500
4        Football Manager 2014   382.185000
5        Football Manager 2010   345.439474
6        Football Manager 2011   333.435294
7  Out of the Park Baseball 16   330.400000
8        Football Manager 2013   310.659615
9        Football Manager 2015   307.381013


In [446]:
copy_df[copy_df['game-title'] == "Football Manager 2012"].sort_values('user-id')

user-id             game-title   value  zero
10715   15415372  Football Manager 2012   595.0     0
12486   18604016  Football Manager 2012    76.0     0
21637   31849177  Football Manager 2012  1168.0     0
28757   40080833  Football Manager 2012   855.0     0
29448   42005897  Football Manager 2012   275.0     0
...          ...                    ...     ...   ...
76551  106454385  Football Manager 2012    32.0     0
76909  107107474  Football Manager 2012    10.1     0
76978  107324790  Football Manager 2012   374.0     0
83398  119721478  Football Manager 2012    14.2     0
92000  140527332  Football Manager 2012    11.3     0

[80 rows x 4 columns]

In [447]:
copy_df.groupby(['user-id', 'game-title']).sum(numeric_only=True).reset_index()

user-id                    game-title  value  zero
0            5250                   Alien Swarm    4.9     0
1            5250               Cities Skylines  144.0     0
2            5250                Counter-Strike    0.0     0
3            5250         Counter-Strike Source    0.0     0
4            5250                 Day of Defeat    0.0     0
...           ...                           ...    ...   ...
128799  309626088  Age of Empires II HD Edition    6.7     0
128800  309812026  Counter-Strike Nexon Zombies    0.0     0
128801  309812026                     Robocraft    0.0     0
128802  309824202                        Dota 2    0.7     0
128803  309903146                        Dota 2    0.2     0

[128804 rows x 4 columns]

**Task 13.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print a DataFrame with the first 10 rows from the entire Steam dataset after this change.

In [448]:
# Write your code here
def sigmoid(x):
    return (1 / (1 + np.exp(-0.01 * x)))

copy_df = steam_df.copy()
condition = copy_df['behavior-name'] == 'play'
copy_df.loc[condition, 'value'] = sigmoid(copy_df.loc[condition, 'value'])
print(copy_df[:10])

     user-id                  game-title behavior-name     value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase  1.000000     0
1  151603712  The Elder Scrolls V Skyrim          play  0.938774     0
2  151603712                   Fallout 4      purchase  1.000000     0
3  151603712                   Fallout 4          play  0.704746     0
4  151603712                       Spore      purchase  1.000000     0
5  151603712                       Spore          play  0.537181     0
6  151603712           Fallout New Vegas      purchase  1.000000     0
7  151603712           Fallout New Vegas          play  0.530213     0
8  151603712               Left 4 Dead 2      purchase  1.000000     0
9  151603712               Left 4 Dead 2          play  0.522235     0


## Pandas tasks - MovieLens dataset

In [449]:
ml_movies_df.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

**Task 14\*.** Calculate popularity (by the number of users who watched a movie) of all genres. Print a DataFrame with two columns: genre, n_users, where n_users contains the number of users who watched a given genre. Sort all genres in descending order.

In [450]:
# Write your code here
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')

In [451]:
# ml_movies_df['genre'] = ml_movies_df['genres'].str.split('|')
# ml_movies_df = ml_movies_df.explode('genre', ignore_index=True)
# ml_movies_df.drop(labels=['genres'],axis=1, inplace=True)
# ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
# ml_df.head()

In [452]:
# res = ml_df.groupby(['genre']).count().sort_values('userId', ascending=False).reset_index()
# res = res[['genre', 'userId']]
# res.columns = ['genre', 'n_users']
# print(res)

**Task 15\*.** Calculate average rating for all genres. Print a DataFrame with two columns: genre, rating, where rating contains the average rating for a given genre. Sort all genres in descending order.

In [453]:
# Write your code here
# res = ml_df.groupby(['genre']).mean().sort_values('rating', ascending=False).reset_index()
# res = res[['genre', 'rating']]
# print(res)

**Task 16.** Calculate each movie rating bias (deviation from the mean of all movies average rating). Print a DataFrame with the first 10 in the form: title, average rating, bias.

In [476]:
# Write your code here
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
mean = ml_df['rating'].mean()
avg_ratings_df = ml_df.groupby(['title'])['rating'].mean().reset_index()
avg_rating = avg_ratings_df['rating'].mean()
avg_ratings_df.rename(columns={'rating': 'average_rating'}, inplace=True)
avg_ratings_df['bias'] = avg_ratings_df['average_rating'] - mean
print(avg_ratings_df[:10])

                                     title  average_rating      bias
0                               '71 (2014)        4.000000  0.498443
1  'Hellboy': The Seeds of Creation (2004)        4.000000  0.498443
2                   'Round Midnight (1986)        3.500000 -0.001557
3                      'Salem's Lot (2004)        5.000000  1.498443
4                'Til There Was You (1997)        4.000000  0.498443
5          'Tis the Season for Love (2015)        1.500000 -2.001557
6                       'burbs, The (1989)        3.176471 -0.325086
7                     'night Mother (1986)        3.000000 -0.501557
8              (500) Days of Summer (2009)        3.666667  0.165110
9           *batteries not included (1987)        3.285714 -0.215843


**Task 17.** Calculate each user rating bias (deviation from the mean of all users average rating). Print a DataFrame with the first 10 in the form: user_id, average rating, bias.

In [482]:
# Write your code here
mean_rating = ml_ratings_df['rating'].mean()
user_ratings_df = ml_ratings_df.groupby(['userId'])['rating'].mean().reset_index()
user_ratings_df.rename(columns={'rating': 'average_rating'}, inplace=True)
user_ratings_df['bias'] = user_ratings_df['average_rating'] - mean_rating
print(user_ratings_df[:10])

   userId  average_rating      bias
0       1        4.366379  0.864822
1       2        3.948276  0.446719
2       3        2.435897 -1.065660
3       4        3.555556  0.053999
4       5        3.636364  0.134807
5       6        3.493631 -0.007926
6       7        3.230263 -0.271294
7       8        3.574468  0.072911
8       9        3.260870 -0.240687
9      10        3.278571 -0.222986


**Task 18.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns. You can iterate over the DataFrame in this task. Alternatively, try using the DataFrame pivot and reindex methods and compare the execution time. Initialize the numpy random number generator with seed=4321.

In [492]:
condition = (ml_df['userId'] == 414) & (ml_df['movieId'] == 2571)
ml_df.loc[condition]

userId  movieId  rating  timestamp               title  \
12828     414     2571     5.0  961514761  Matrix, The (1999)   

                       genres  
12828  Action|Sci-Fi|Thriller

In [519]:
# Write your code here

user_ids = ml_df['userId'].unique()
movie_ids = ml_df['movieId'].unique()
rng = np.random.RandomState(seed=4321)
user_ids = sorted(list(rng.choice(user_ids, size=10)))
movie_ids = sorted(list(rng.choice(movie_ids, size=10)))
movie_titles = [ml_movies_df.loc[ml_movies_df['movieId'] == movie_id, 'title'].tolist()[0] for movie_id in movie_ids]

interaction_matrix = np.zeros(100).reshape(10, 10)
for i, u_id in enumerate(user_ids):
    for j, m_id in enumerate(movie_ids):
        condition = (ml_df['userId'] == u_id) & (ml_df['movieId'] == m_id)
        if not ml_df.loc[condition].empty:
            interaction_matrix[i, j] = 1.0
result_df = pd.DataFrame(data=interaction_matrix, columns=movie_titles)
result_df = result_df.set_index(pd.Index(user_ids))
print(result_df)

     Father of the Bride (1950)  Matrix, The (1999)  Howards End (1992)  \
11                          0.0                 0.0                 0.0   
277                         0.0                 0.0                 0.0   
286                         0.0                 1.0                 0.0   
357                         0.0                 0.0                 0.0   
414                         0.0                 1.0                 0.0   
428                         0.0                 1.0                 0.0   
470                         0.0                 0.0                 0.0   
487                         0.0                 1.0                 0.0   
543                         0.0                 1.0                 0.0   
544                         0.0                 0.0                 0.0   

     Thirteen Conversations About One Thing (a.k.a. 13 Conversations) (2001)  \
11                                                 0.0                         
277           

## Pandas + numpy tasks

**Task 19.** Create the entire interaction matrix (2D numpy array) for the MovieLens dataset. Print the submatrix of the first 10 rows and 10 columns.

In [575]:
# Write your code here
interaction_matrix_df = ml_df.pivot_table(index='userId', columns='movieId', values='rating', fill_value=0.0)
res = np.array(interaction_matrix_df)
res[res > 0.0] = 1.0
res = np.vstack([np.zeros(res.shape[1]), res])
res = np.hstack([np.zeros(res.shape[0]).reshape(-1, 1), res])
print(res[:10, :10])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Task 20.** Calculate the matrix of size (n_users, n_users) where at position (i, j) there is the number of movies watched both by user i and user j. Use a single matrix multiplication to obtain the result. Print the submatrix of first 10 rows and 10 columns.

In [594]:
# Write your code here

interaction_matrix_df = ml_df.pivot_table(index='userId', columns='movieId', values='rating', fill_value=0.0)
res = np.array(interaction_matrix_df)
res = np.vstack([np.zeros(res.shape[1]), res])
res = np.hstack([np.zeros(res.shape[0]).reshape(-1, 1), res])
res[res > 0.0] = 1.0
res = np.matmul(res, np.transpose(res)).astype(float)
print(res[:10, :10])

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 232.   2.   7.  45.  13.  33.  26.  15.   5.]
 [  0.   2.  29.   0.   1.   1.   2.   3.   1.   0.]
 [  0.   7.   0.  39.   1.   1.   3.   0.   1.   0.]
 [  0.  45.   1.   1. 216.  12.  27.  22.   9.   1.]
 [  0.  13.   1.   1.  12.  44.  36.   9.  19.   0.]
 [  0.  33.   2.   3.  27.  36. 314.  14.  44.   2.]
 [  0.  26.   3.   0.  22.   9.  14. 152.   8.   6.]
 [  0.  15.   1.   1.   9.  19.  44.   8.  47.   0.]
 [  0.   5.   0.   0.   1.   0.   2.   6.   0.  46.]]


**Task 21.** Calculate the matrix of size (n_items, n_items) where at position (i, j) there is the number of users who watched both movie i and movie j. Use a single matrix multiplication to obtain the result. To prevent memory error use only the first 1000 items. Print the submatrix of first 10 rows and 10 columns.

In [600]:
# Write your code here

interaction_matrix_df = ml_df.pivot_table(index='userId', columns='movieId', values='rating', fill_value=0.0)
res = np.array(interaction_matrix_df)[:1000, :1000]
res = np.vstack([np.zeros(res.shape[1]), res])
res = np.hstack([np.zeros(res.shape[0]).reshape(-1, 1), res])
res[res > 0.0] = 1.0
res = np.matmul(np.transpose(res), res).astype(float)
print(res[:10, :10])

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 215.  68.  32.   2.  32.  58.  32.   5.  12.]
 [  0.  68. 110.  26.   3.  22.  36.  18.   6.   3.]
 [  0.  32.  26.  52.   1.  19.  25.  19.   4.   9.]
 [  0.   2.   3.   1.   7.   3.   2.   6.   1.   0.]
 [  0.  32.  22.  19.   3.  49.  24.  23.   4.   9.]
 [  0.  58.  36.  25.   2.  24. 102.  22.   5.   9.]
 [  0.  32.  18.  19.   6.  23.  22.  54.   4.   5.]
 [  0.   5.   6.   4.   1.   4.   5.   4.   8.   0.]
 [  0.  12.   3.   9.   0.   9.   9.   5.   0.  16.]]
